#!/usr/bin/env python3
"""Generate src/stations.h from the Caltrain GTFS static feed.

The station list and the holiday calendar are facts owned by Caltrain, not by us.
Hand-typing them invites transcription errors — and one such error (assuming a
stop_id direction) is exactly what prompted this project's design. So we derive
the table from the authoritative feed and regenerate rather than edit by hand.

Caltrain changes its schedule a few times a year. When it does:

    python3 tools/gen_stations.py            # downloads the current feed
    python3 tools/gen_stations.py --zip x.z  # or point at a local copy

The generated header is committed, so a build never needs the network.
"""

import argparse
import csv
import io
import pathlib
import re
import sys
import urllib.request
import zipfile

# Trillium publishes Caltrain's official GTFS feed. Unauthenticated, ~180 KB.
GTFS_URL = "https://data.trilliumtransit.com/gtfs/caltrain-ca-us/caltrain-ca-us.zip"

# Platform stop_ids are 5 digits: a 4-digit station base plus a direction digit.
# 70011 = base 7001 (San Francisco) + 1 (northbound); 70012 is its southbound twin.
PLATFORM_STOP_RE = re.compile(r"^(\d{4})([12])$")

# GTFS station names carry a direction suffix we don't want in the UI.
NAME_SUFFIX_RE = re.compile(r"\s+Caltrain\s+(Northbound|Southbound)\s*$", re.I)

HEADER_PATH = pathlib.Path(__file__).resolve().parent.parent / "src" / "stations.h"


def load_gtfs(zip_path: str | None) -> zipfile.ZipFile:
    """Return the GTFS archive, downloading it unless a local path was given."""
    if zip_path:
        return zipfile.ZipFile(zip_path)
    print(f"downloading {GTFS_URL}", file=sys.stderr)
    with urllib.request.urlopen(GTFS_URL, timeout=60) as resp:
        return zipfile.ZipFile(io.BytesIO(resp.read()))


def read_csv(gtfs: zipfile.ZipFile, name: str) -> list[dict]:
    """Read one GTFS .txt file as a list of dicts, tolerating a UTF-8 BOM."""
    with gtfs.open(name) as fh:
        text = io.TextIOWrapper(fh, encoding="utf-8-sig")
        return list(csv.DictReader(text))


def collect_stations(gtfs: zipfile.ZipFile) -> list[tuple[int, str, float]]:
    """Return [(base_code, display_name, latitude)] for every Caltrain station.

    A station appears in stops.txt twice — once per direction platform. We fold
    the pair into a single entry keyed by the 4-digit base, because the UI picks
    a *station* and the firmware derives the platform from travel direction.
    """
    stations: dict[int, tuple[str, float]] = {}
    for row in read_csv(gtfs, "stops.txt"):
        match = PLATFORM_STOP_RE.match(row["stop_id"].strip())
        if not match:
            continue  # parent stations and non-platform records
        base = int(match.group(1))
        name = NAME_SUFFIX_RE.sub("", row["stop_name"]).strip()
        stations.setdefault(base, (name, float(row["stop_lat"])))

    # Sort by latitude descending = geographically north to south. We use the
    # real coordinates rather than trusting the base codes to be monotonic,
    # since the numbering has gaps (7015 = the closed Atherton station) and a
    # future infill station could land out of order.
    ordered = sorted(stations.items(), key=lambda kv: -kv[1][1])
    return [(base, name, lat) for base, (name, lat) in ordered]


def c_string(value: str) -> str:
    """Escape a Python string for use as a C string literal."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(stations, feed_version: str) -> str:
    name_width = max(len(c_string(n)) for _, n, _ in stations)

    lines = [
        "// GENERATED by tools/gen_stations.py — do not edit by hand.",
        f"// Source: {GTFS_URL}",
        f"// Feed version: {feed_version}",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "// A Caltrain station, identified by the 4-digit base of its GTFS stop_id.",
        "// The two platform stop_ids are base*10 + 1 (northbound) and + 2 (southbound);",
        "// see stationStopId() in route.h, which is the ONLY place that mapping lives.",
        "struct Station {",
        "  const char* name;",
        "  uint16_t    base;",
        "};",
        "",
        "// Ordered north to south by latitude. That ordering is load-bearing: a trip",
        "// whose origin index is less than its destination index travels southbound.",
        "inline constexpr Station kStations[] = {",
    ]
    for base, name, lat in stations:
        lit = c_string(name)
        lines.append(f"    {{{lit:<{name_width}}, {base}}},  // {lat:.6f}")
    lines += [
        "};",
        f"inline constexpr int kStationCount = {len(stations)};",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--zip", help="path to a local GTFS zip instead of downloading")
    parser.add_argument("-o", "--output", default=str(HEADER_PATH))
    args = parser.parse_args()

    gtfs = load_gtfs(args.zip)
    stations = collect_stations(gtfs)
    feed_version = read_csv(gtfs, "feed_info.txt")[0].get("feed_version", "unknown")

    if not stations:
        print("error: no platform stops found — feed format may have changed", file=sys.stderr)
        return 1

    out = pathlib.Path(args.output)
    out.write_text(render(stations, feed_version))
    print(f"wrote {out} — {len(stations)} stations (feed {feed_version})", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
