// GENERATED by tools/gen_stations.py — do not edit by hand.
// Source: https://data.trilliumtransit.com/gtfs/caltrain-ca-us/caltrain-ca-us.zip
// Feed version: UTC: 10-Jun-2026 22:25
#pragma once
#include <stdint.h>

// A Caltrain station, identified by the 4-digit base of its GTFS stop_id.
// The two platform stop_ids are base*10 + 1 (northbound) and + 2 (southbound);
// see stationStopId() in route.h, which is the ONLY place that mapping lives.
struct Station {
  const char* name;
  uint16_t    base;
};

// Ordered north to south by latitude. That ordering is load-bearing: a trip
// whose origin index is less than its destination index travels southbound.
inline constexpr Station kStations[] = {
    {"San Francisco"      , 7001},  // 37.776390
    {"22nd Street"        , 7002},  // 37.757599
    {"Bayshore"           , 7003},  // 37.709537
    {"South San Francisco", 7004},  // 37.655941
    {"San Bruno"          , 7005},  // 37.630500
    {"Millbrae"           , 7006},  // 37.599880
    {"Broadway"           , 7007},  // 37.587640
    {"Burlingame"         , 7008},  // 37.580197
    {"San Mateo"          , 7009},  // 37.568087
    {"Hayward Park"       , 7010},  // 37.552938
    {"Hillsdale"          , 7011},  // 37.542608
    {"Belmont"            , 7012},  // 37.520890
    {"San Carlos"         , 7013},  // 37.508050
    {"Redwood City"       , 7014},  // 37.486159
    {"Menlo Park"         , 7016},  // 37.454856
    {"Palo Alto"          , 7017},  // 37.443475
    {"California Avenue"  , 7019},  // 37.429365
    {"San Antonio"        , 7020},  // 37.407332
    {"Mountain View"      , 7021},  // 37.394459
    {"Sunnyvale"          , 7022},  // 37.378916
    {"Lawrence"           , 7023},  // 37.370598
    {"Santa Clara"        , 7024},  // 37.353238
    {"College Park"       , 7025},  // 37.342384
    {"San Jose Diridon"   , 7026},  // 37.329239
    {"Tamien"             , 7027},  // 37.311740
    {"Capitol"            , 7028},  // 37.284102
    {"Blossom Hill"       , 7029},  // 37.252422
    {"Morgan Hill"        , 7030},  // 37.129363
    {"San Martin"         , 7031},  // 37.085225
    {"Gilroy"             , 7032},  // 37.003538
};
inline constexpr int kStationCount = 30;
